# Generated by Django 2.2.14 on 2020-10-21 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_token', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_source.DataSource', verbose_name='数据源'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
